### ISSUE TITLE
App throws an exception and crashes

### ISSUE THREAD

**Issue by gavrilmikhailov** [Slins-23/flutter-fft#1] opened 2020-04-27 09:03 UTC
## Plugin version
1.0.1
## flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287,
    locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.44.2)
[✓] Connected device (1 available)

• No issues found!
## Tested environment
- HTC One M8 Real Device
## Steps to reproduce the behavior
I just ran an example code and it seems to be working for a 15-20 seconds. Then the app crashes with this:

```
Restarted application in 1 622ms.
D/FlutterFftPlugin( 6146): KOKOKOKKOK, Excep: java.lang.IndexOutOfBoundsException: Index: 96, Size: 96
D/FlutterFftPlugin( 6146): Exception: java.lang.IllegalStateException: Reply already submitted
D/AndroidRuntime( 6146): Shutting down VM
E/AndroidRuntime( 6146): FATAL EXCEPTION: main
E/AndroidRuntime( 6146): Process: com.example.tuner_app, PID: 6146
E/AndroidRuntime( 6146): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 6146): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:148)
E/AndroidRuntime( 6146): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:239)
E/AndroidRuntime( 6146): 	at com.slins.flutterfft.PitchModel.updateFrequencyAndNote(PitchModel.java:90)
E/AndroidRuntime( 6146): 	at com.slins.flutterfft.FlutterFftPlugin.lambda$startRecorder$2$FlutterFftPlugin(FlutterFftPlugin.java:132)
E/AndroidRuntime( 6146): 	at com.slins.flutterfft.-$$Lambda$FlutterFftPlugin$hUYDhPUP8CnO0Q6jSiEqk8q7Idw.run(Unknown Source:4)
E/AndroidRuntime( 6146): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime( 6146): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 6146): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 6146): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime( 6146): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6146): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
E/AndroidRuntime( 6146): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/Process ( 6146): Sending signal. PID: 6146 SIG: 9
Lost connection to device.
Exited (sigterm)
```

Any ideas how to resolve ?

**Comment by AseemWangoo** [comment] 2020-07-08 00:08
Try to add these lines

FlutterFft _flutterFft = FlutterFft();

@override
  void dispose() {
    _flutterFft?.stopRecorder();
    super.dispose();
  }

**Comment by andHW** [comment] 2020-07-08 09:43
> Try to add these lines
> 
> FlutterFft _flutterFft = FlutterFft();
> 
> @override
> void dispose() {
> _flutterFft?.stopRecorder();
> super.dispose();
> }

I tried to add these lines.
For me, the app would not crash suddenly after 15~20 seconds.
But once I press the back key (I am running the sample code on pushed page), it crashes.

**Comment by marciofrayze** [comment] 2020-07-31 16:55
Same problem here, but not always. Sometime it works, sometime it doesn't. Same code. Just ran flutter run again and it works.

Guess it's something related to the order of execution of some async code?

Running on a physical device (Motorola G5S).

❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Android Studio (not installed)
[✓] Connected device (1 available)

edit: I guess the problem is that in your example you are calling an async code from inside initState.

**Comment by Slins-23** [comment] 2021-06-26 02:02
This specific issue and some others are probably fixed now, as I encountered the same issue when updating the repository.

Sorry for the late response, I just couldn't and still can't pay much attention to my repos.
I just updated a few things and refactored the code, so it's probably fixed now.

**Closed as completed** 2021-12-07 15:25 UTC
